/**
 * Curated department dependencies based on Spec §8 Cross-Department Workflows.
 * Maps each department to a set of interrelated departments for realistic workflow transitions.
 */

export const BDT_DEPARTMENT_DEPENDENCIES: Record<string, string[]> = {
  dept_product: ['dept_engineering', 'dept_design', 'dept_marketing', 'dept_data'],
  dept_engineering: ['dept_product', 'dept_design', 'dept_security', 'dept_operations'],
  dept_sales: ['dept_legal', 'dept_product', 'dept_finance', 'dept_customer_success'],
  dept_marketing: ['dept_design', 'dept_sales', 'dept_customer_success', 'dept_product'],
  dept_hr: ['dept_finance', 'dept_operations', 'dept_strategy'],
  dept_finance: ['dept_legal', 'dept_sales', 'dept_strategy'],
  dept_operations: ['dept_engineering', 'dept_finance', 'dept_customer_success'],
  dept_data: ['dept_engineering', 'dept_product', 'dept_strategy'],
  dept_design: ['dept_product', 'dept_engineering', 'dept_marketing'],
  dept_security: ['dept_engineering', 'dept_operations', 'dept_legal'],
  dept_customer_success: ['dept_sales', 'dept_product', 'dept_operations'],
  dept_legal: ['dept_finance', 'dept_sales', 'dept_security'],
  dept_strategy: ['dept_finance', 'dept_hr', 'dept_product'],
};

/**
 * Curated overrides for specific leaf nodes to make the trails feel extremely realistic.
 * These map to the exact node IDs generated by buildTree in bdtDepartmentSeed.ts.
 */
export const BDT_NODE_DEPENDENCY_OVERRIDES: Record<string, string[]> = {
  // Product -> Enterprise Tier project (Projects is at index 1 -> prd_d1_1, Enterprise Tier is at index 3 -> prd_d1_1_d2_3)
  'prd_d1_1_d2_3': ['dept_engineering', 'dept_design', 'dept_sales', 'dept_data'],
  // Release engineering path -> Schedule release action (Release Engineering is branch index 1 -> eng_d1_3, Schedule release is leaf index 0 -> eng_d1_3_d2_0)
  'eng_d1_3_d2_0': ['dept_product', 'dept_security', 'dept_operations'],
  // Proposal & Negotiation branch (branch index 2 -> sal_d1_4): Discount approval (leaf index 0) & Send proposal (leaf index 1)
  'sal_d1_4_d2_0': ['dept_legal', 'dept_finance', 'dept_customer_success'],
  'sal_d1_4_d2_1': ['dept_legal', 'dept_finance', 'dept_customer_success'],
  // Campaign path -> Launch campaign action (Demand Generation is branch index 1 -> mkt_d1_3, Launch campaign is leaf index 0 -> mkt_d1_3_d2_0)
  'mkt_d1_3_d2_0': ['dept_design', 'dept_customer_success', 'dept_product'],
  // Incident path -> Critical vulnerability signal (Application Security is branch index 1 -> sec_d1_3, Critical vulnerability is leaf index 0 -> sec_d1_3_d2_0)
  'sec_d1_3_d2_0': ['dept_engineering', 'dept_operations', 'dept_customer_success'],
};
