import type { CompanyRecord } from './schema';

/* ================================================================
   Real-world companies — India + Global, public + private.
   offset3D is relative to the parent industry's position3D.
   Data is approximate/public-domain as of 2024-2025.
================================================================ */

/* Reusable offset sets — spread companies across a small sphere */
const O = {
  a: [8,  2,  2] as [number,number,number],
  b: [-7, 4, -5] as [number,number,number],
  c: [7, -3, -6] as [number,number,number],
  d: [4,  7, -8] as [number,number,number],
  e: [-5,-6,  5] as [number,number,number],
  f: [6,  5,  4] as [number,number,number],
  g: [-4, 8, -3] as [number,number,number],
  h: [5, -7, -1] as [number,number,number],
  i: [2,  1,  2] as [number,number,number],   // reserved for comp-you (center-ish)
};

export const COMPANIES: CompanyRecord[] = [

  /* ──────────── SaaS ──────────── */
  {
    id: 'comp-you',
    name: 'FounderOS',
    industryId: 'ind-saas',
    country: 'India',
    founded: 2024,
    stage: 'Seed',
    isPublic: false,
    valuation: '—',
    mrrUSD: 8500,
    employees: 12,
    investors: ['Angel'],
    description: 'Digital twin OS for startups — your company',
    status: 'healthy',
    offset3D: O.i,
  },
  {
    id: 'comp-freshworks',
    name: 'Freshworks',
    industryId: 'ind-saas',
    country: 'India',
    founded: 2010,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'FRSH',
    valuation: '3.5B',
    mrrUSD: 180_000_000,
    employees: 5400,
    investors: ['Accel', 'Tiger Global', 'Sequoia'],
    description: 'CRM, ITSM, and customer support SaaS suite',
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-zoho',
    name: 'Zoho',
    industryId: 'ind-saas',
    country: 'India',
    founded: 1996,
    stage: 'Bootstrapped',
    isPublic: false,
    valuation: '15B',
    mrrUSD: 120_000_000,
    employees: 15000,
    investors: [],
    description: 'Full-stack business SaaS — CRM, finance, HR, productivity',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-chargebee',
    name: 'Chargebee',
    industryId: 'ind-saas',
    country: 'India',
    founded: 2011,
    stage: 'Series D+',
    isPublic: false,
    valuation: '3.5B',
    mrrUSD: 8_500_000,
    employees: 1000,
    investors: ['Insight Partners', 'Tiger Global', 'Steadview'],
    description: 'Subscription billing and revenue management platform',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-postman',
    name: 'Postman',
    industryId: 'ind-saas',
    country: 'India',
    founded: 2014,
    stage: 'Series D+',
    isPublic: false,
    valuation: '5.6B',
    mrrUSD: 12_000_000,
    employees: 800,
    investors: ['CRV', 'Nexus', 'Insight Partners'],
    description: 'API development and collaboration platform',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-browserstack',
    name: 'BrowserStack',
    industryId: 'ind-saas',
    country: 'India',
    founded: 2011,
    stage: 'Series B',
    isPublic: false,
    valuation: '4B',
    mrrUSD: 7_000_000,
    employees: 1200,
    investors: ['Bond Capital', 'Accel'],
    description: 'Cloud platform for web and mobile testing',
    status: 'healthy',
    offset3D: O.e,
  },
  {
    id: 'comp-salesforce',
    name: 'Salesforce',
    industryId: 'ind-saas',
    country: 'USA',
    founded: 1999,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'CRM',
    valuation: '200B',
    mrrUSD: 2_500_000_000,
    employees: 73000,
    investors: [],
    description: 'World\'s #1 CRM platform — cloud sales, service, marketing',
    status: 'healthy',
    offset3D: O.f,
  },
  {
    id: 'comp-hubspot',
    name: 'HubSpot',
    industryId: 'ind-saas',
    country: 'USA',
    founded: 2006,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'HUBS',
    valuation: '20B',
    mrrUSD: 170_000_000,
    employees: 8000,
    investors: [],
    description: 'Inbound marketing, sales, and CRM platform',
    status: 'healthy',
    offset3D: O.g,
  },

  /* ──────────── FinTech ──────────── */
  {
    id: 'comp-razorpay',
    name: 'Razorpay',
    industryId: 'ind-fintech',
    country: 'India',
    founded: 2014,
    stage: 'Series F',
    isPublic: false,
    valuation: '7.5B',
    mrrUSD: 20_000_000,
    employees: 3500,
    investors: ['Sequoia', 'Tiger Global', 'GIC', 'Alkeon'],
    description: 'India\'s leading payment gateway and business banking platform',
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-phonepe',
    name: 'PhonePe',
    industryId: 'ind-fintech',
    country: 'India',
    founded: 2015,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '12B',
    mrrUSD: 35_000_000,
    employees: 5000,
    investors: ['Walmart', 'Tiger Global', 'General Atlantic'],
    description: 'UPI payments, insurance, mutual funds — 500M+ users',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-groww',
    name: 'Groww',
    industryId: 'ind-fintech',
    country: 'India',
    founded: 2016,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '3B',
    mrrUSD: 18_000_000,
    employees: 3000,
    investors: ['Sequoia', 'Tiger Global', 'YC', 'Ribbit Capital'],
    description: 'Stock trading, mutual funds, and digital investing platform',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-paytm',
    name: 'Paytm',
    industryId: 'ind-fintech',
    country: 'India',
    founded: 2010,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'PAYTM.NS',
    valuation: '5B',
    mrrUSD: 60_000_000,
    employees: 9000,
    investors: ['Alibaba', 'SoftBank', 'Berkshire Hathaway'],
    description: 'Payments, financial services, and commerce platform',
    status: 'warning',
    offset3D: O.d,
  },
  {
    id: 'comp-stripe',
    name: 'Stripe',
    industryId: 'ind-fintech',
    country: 'USA',
    founded: 2010,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '65B',
    mrrUSD: 1_000_000_000,
    employees: 8000,
    investors: ['Sequoia', 'Andreessen Horowitz', 'Thrive Capital'],
    description: 'Global payments infrastructure for internet businesses',
    status: 'healthy',
    offset3D: O.e,
  },
  {
    id: 'comp-revolut',
    name: 'Revolut',
    industryId: 'ind-fintech',
    country: 'UK',
    founded: 2015,
    stage: 'Series E',
    isPublic: false,
    valuation: '33B',
    mrrUSD: 280_000_000,
    employees: 8000,
    investors: ['SoftBank', 'Tiger Global', 'TCV'],
    description: 'Super-app for money — banking, crypto, stock trading',
    status: 'healthy',
    offset3D: O.f,
  },
  {
    id: 'comp-nubank',
    name: 'Nubank',
    industryId: 'ind-fintech',
    country: 'Brazil',
    founded: 2013,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'NU',
    valuation: '30B',
    mrrUSD: 450_000_000,
    employees: 7000,
    investors: ['Sequoia', 'Tiger Global', 'Berkshire Hathaway'],
    description: 'Latin America\'s largest digital bank — 100M+ customers',
    status: 'healthy',
    offset3D: O.g,
  },
  {
    id: 'comp-zerodha',
    name: 'Zerodha',
    industryId: 'ind-fintech',
    country: 'India',
    founded: 2010,
    stage: 'Bootstrapped',
    isPublic: false,
    valuation: '3.6B',
    mrrUSD: 22_000_000,
    employees: 1200,
    investors: [],
    description: 'India\'s largest stock broker — discount brokerage pioneer',
    status: 'healthy',
    offset3D: O.h,
  },

  /* ──────────── HealthTech ──────────── */
  {
    id: 'comp-practo',
    name: 'Practo',
    industryId: 'ind-healthtech',
    country: 'India',
    founded: 2008,
    stage: 'Series D+',
    isPublic: false,
    valuation: '1.5B',
    mrrUSD: 5_000_000,
    employees: 1500,
    investors: ['Sequoia', 'Tencent', 'Matrix Partners'],
    description: 'Online doctor consultations, clinic management, health records',
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-pharmeasy',
    name: 'PharmEasy',
    industryId: 'ind-healthtech',
    country: 'India',
    founded: 2014,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '5.6B',
    mrrUSD: 45_000_000,
    employees: 5000,
    investors: ['Prosus', 'TPG', 'Temasek'],
    description: 'Online pharmacy, diagnostics, and teleconsultation platform',
    status: 'warning',
    offset3D: O.b,
  },
  {
    id: 'comp-1mg',
    name: 'Tata 1mg',
    industryId: 'ind-healthtech',
    country: 'India',
    founded: 2015,
    stage: 'Series D+',
    isPublic: false,
    valuation: '2.5B',
    mrrUSD: 30_000_000,
    employees: 3000,
    investors: ['Tata Group', 'IFC', 'Epiq Capital'],
    description: 'e-pharmacy, diagnostics, online doctor, and health content',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-cult',
    name: 'Cult.fit',
    industryId: 'ind-healthtech',
    country: 'India',
    founded: 2016,
    stage: 'Series F',
    isPublic: false,
    valuation: '1.5B',
    mrrUSD: 12_000_000,
    employees: 3000,
    investors: ['Accel', 'Flipkart', 'Reckitt', 'Kalaari'],
    description: 'Omnichannel fitness — gym chain, live classes, nutrition',
    status: 'warning',
    offset3D: O.d,
  },
  {
    id: 'comp-apollohealth',
    name: 'Apollo 24/7',
    industryId: 'ind-healthtech',
    country: 'India',
    founded: 2020,
    stage: 'Series B',
    isPublic: false,
    valuation: '2B',
    mrrUSD: 8_000_000,
    employees: 2000,
    investors: ['Apollo Hospitals', 'Evolvence', 'Neuberger Berman'],
    description: 'Teleconsultation and digital health arm of Apollo Hospitals',
    status: 'healthy',
    offset3D: O.e,
  },
  {
    id: 'comp-portea',
    name: 'Portea Medical',
    industryId: 'ind-healthtech',
    country: 'India',
    founded: 2013,
    stage: 'Series C',
    isPublic: false,
    valuation: '0.5B',
    mrrUSD: 3_000_000,
    employees: 900,
    investors: ['Accel', 'IFC', 'Qualcomm Ventures'],
    description: 'Home healthcare services — nursing, physiotherapy, diagnostics',
    status: 'healthy',
    offset3D: O.f,
  },

  /* ──────────── EdTech ──────────── */
  {
    id: 'comp-byjus',
    name: "BYJU'S",
    industryId: 'ind-edtech',
    country: 'India',
    founded: 2011,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '8B',
    mrrUSD: 100_000_000,
    employees: 25000,
    investors: ['Sequoia', 'Chan Zuckerberg', 'Silver Lake', 'Qatar Investment'],
    description: 'India\'s largest K-12 online learning app — 150M+ learners',
    status: 'warning',
    offset3D: O.a,
  },
  {
    id: 'comp-unacademy',
    name: 'Unacademy',
    industryId: 'ind-edtech',
    country: 'India',
    founded: 2015,
    stage: 'Series F',
    isPublic: false,
    valuation: '3.4B',
    mrrUSD: 15_000_000,
    employees: 3500,
    investors: ['SoftBank', 'Tiger Global', 'Sequoia', 'Facebook'],
    description: 'Test prep platform for UPSC, JEE, NEET, and competitive exams',
    status: 'warning',
    offset3D: O.b,
  },
  {
    id: 'comp-vedantu',
    name: 'Vedantu',
    industryId: 'ind-edtech',
    country: 'India',
    founded: 2014,
    stage: 'Series E',
    isPublic: false,
    valuation: '1B',
    mrrUSD: 5_000_000,
    employees: 2000,
    investors: ['ABC World Asia', 'Coatue', 'Tiger Global'],
    description: 'Live online tutoring and interactive learning platform',
    status: 'warning',
    offset3D: O.c,
  },
  {
    id: 'comp-upgrad',
    name: 'upGrad',
    industryId: 'ind-edtech',
    country: 'India',
    founded: 2015,
    stage: 'Series F',
    isPublic: false,
    valuation: '2.25B',
    mrrUSD: 20_000_000,
    employees: 4500,
    investors: ['IFC', 'IIFL', 'Temasek', 'Lakshmi Mittal'],
    description: 'Higher education and professional upskilling — working adults',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-duolingo',
    name: 'Duolingo',
    industryId: 'ind-edtech',
    country: 'USA',
    founded: 2011,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'DUOL',
    valuation: '8B',
    mrrUSD: 55_000_000,
    employees: 700,
    investors: [],
    description: 'Gamified language learning app — 600M+ registered users',
    status: 'healthy',
    offset3D: O.e,
  },
  {
    id: 'comp-coursera',
    name: 'Coursera',
    industryId: 'ind-edtech',
    country: 'USA',
    founded: 2012,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'COUR',
    valuation: '5B',
    mrrUSD: 130_000_000,
    employees: 1000,
    investors: [],
    description: 'Online degrees and professional certificates from top universities',
    status: 'healthy',
    offset3D: O.f,
  },

  /* ──────────── E-Commerce ──────────── */
  {
    id: 'comp-flipkart',
    name: 'Flipkart',
    industryId: 'ind-ecommerce',
    country: 'India',
    founded: 2007,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '35B',
    mrrUSD: 700_000_000,
    employees: 30000,
    investors: ['Walmart (81%)', 'Tiger Global', 'Accel'],
    description: "India's largest homegrown e-commerce marketplace",
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-meesho',
    name: 'Meesho',
    industryId: 'ind-ecommerce',
    country: 'India',
    founded: 2015,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '4.9B',
    mrrUSD: 120_000_000,
    employees: 15000,
    investors: ['SoftBank', 'Prosus', 'Sequoia', 'Facebook'],
    description: 'Social commerce for Bharat — reseller + direct marketplace',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-nykaa',
    name: 'Nykaa',
    industryId: 'ind-ecommerce',
    country: 'India',
    founded: 2012,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'NYKAA.NS',
    valuation: '4B',
    mrrUSD: 65_000_000,
    employees: 4500,
    investors: [],
    description: 'Beauty and wellness omni-channel retailer — D2C + marketplace',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-amazon-in',
    name: 'Amazon India',
    industryId: 'ind-ecommerce',
    country: 'India',
    founded: 2013,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'AMZN',
    valuation: '1600B',
    mrrUSD: 5_000_000_000,
    employees: 1_600_000,
    investors: [],
    description: 'India operation of the world\'s largest e-commerce company',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-myntra',
    name: 'Myntra',
    industryId: 'ind-ecommerce',
    country: 'India',
    founded: 2007,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '4B',
    mrrUSD: 90_000_000,
    employees: 5000,
    investors: ['Flipkart (acquired)'],
    description: 'India\'s largest online fashion and lifestyle retailer',
    status: 'healthy',
    offset3D: O.e,
  },
  {
    id: 'comp-jiomart',
    name: 'JioMart',
    industryId: 'ind-ecommerce',
    country: 'India',
    founded: 2020,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '10B',
    mrrUSD: 200_000_000,
    employees: 10000,
    investors: ['Reliance Industries'],
    description: 'Reliance\'s omni-channel retail and grocery platform',
    status: 'healthy',
    offset3D: O.f,
  },

  /* ──────────── AI / ML ──────────── */
  {
    id: 'comp-openai',
    name: 'OpenAI',
    industryId: 'ind-aiml',
    country: 'USA',
    founded: 2015,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '157B',
    mrrUSD: 200_000_000,
    employees: 1700,
    investors: ['Microsoft', 'Thrive Capital', 'Khosla Ventures'],
    description: 'Creator of GPT-4, ChatGPT, DALL-E — leading AI lab',
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-anthropic',
    name: 'Anthropic',
    industryId: 'ind-aiml',
    country: 'USA',
    founded: 2021,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '61B',
    mrrUSD: 100_000_000,
    employees: 800,
    investors: ['Google', 'Amazon', 'Spark Capital'],
    description: 'Safety-focused AI — Claude models, Constitutional AI',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-sarvam',
    name: 'Sarvam AI',
    industryId: 'ind-aiml',
    country: 'India',
    founded: 2023,
    stage: 'Series A',
    isPublic: false,
    valuation: '0.5B',
    mrrUSD: 500_000,
    employees: 120,
    investors: ['Peak XV', 'Lightspeed', 'Khosla Ventures'],
    description: 'India\'s sovereign AI — multilingual LLMs for 22 Indic languages',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-krutrim',
    name: 'Krutrim',
    industryId: 'ind-aiml',
    country: 'India',
    founded: 2023,
    stage: 'Seed',
    isPublic: false,
    valuation: '1B',
    mrrUSD: 300_000,
    employees: 80,
    investors: ['Ola (Bhavish Aggarwal)', 'Matrix Partners'],
    description: 'India\'s first AI unicorn — chips + LLMs for Bharat',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-cohere',
    name: 'Cohere',
    industryId: 'ind-aiml',
    country: 'Canada',
    founded: 2019,
    stage: 'Series D+',
    isPublic: false,
    valuation: '5.5B',
    mrrUSD: 20_000_000,
    employees: 350,
    investors: ['Salesforce', 'Oracle', 'NVIDIA', 'Index Ventures'],
    description: 'Enterprise NLP APIs — search, generation, classification',
    status: 'healthy',
    offset3D: O.e,
  },
  {
    id: 'comp-mistral',
    name: 'Mistral AI',
    industryId: 'ind-aiml',
    country: 'France',
    founded: 2023,
    stage: 'Series B',
    isPublic: false,
    valuation: '6B',
    mrrUSD: 15_000_000,
    employees: 80,
    investors: ['a16z', 'Lightspeed', 'General Catalyst', 'BNP Paribas'],
    description: 'Open-weight European LLMs — efficiency-first foundation models',
    status: 'healthy',
    offset3D: O.f,
  },
  {
    id: 'comp-perplexity',
    name: 'Perplexity',
    industryId: 'ind-aiml',
    country: 'USA',
    founded: 2022,
    stage: 'Series C',
    isPublic: false,
    valuation: '9B',
    mrrUSD: 8_000_000,
    employees: 100,
    investors: ['IVP', 'NVIDIA', 'Bezos Expeditions', 'NEA'],
    description: 'AI-first answer engine replacing traditional web search',
    status: 'healthy',
    offset3D: O.g,
  },

  /* ──────────── CleanTech ──────────── */
  {
    id: 'comp-olaelec',
    name: 'Ola Electric',
    industryId: 'ind-cleantech',
    country: 'India',
    founded: 2017,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'OLAELEC.NS',
    valuation: '4B',
    mrrUSD: 80_000_000,
    employees: 4000,
    investors: ['SoftBank', 'Tiger Global', 'Temasek'],
    description: "India's #1 electric two-wheeler manufacturer",
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-adanigreen',
    name: 'Adani Green',
    industryId: 'ind-cleantech',
    country: 'India',
    founded: 2015,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'ADANIGREEN.NS',
    valuation: '35B',
    mrrUSD: 900_000_000,
    employees: 3500,
    investors: ['Adani Group', 'Total Energies'],
    description: 'India\'s largest renewable energy developer — solar + wind',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-tesla',
    name: 'Tesla',
    industryId: 'ind-cleantech',
    country: 'USA',
    founded: 2003,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'TSLA',
    valuation: '900B',
    mrrUSD: 7_500_000_000,
    employees: 127000,
    investors: [],
    description: 'Electric vehicles, energy storage, solar roof — carbon mission',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-renew',
    name: 'ReNew Energy',
    industryId: 'ind-cleantech',
    country: 'India',
    founded: 2011,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'RNW',
    valuation: '3B',
    mrrUSD: 200_000_000,
    employees: 3000,
    investors: ['Goldman Sachs', 'ADIA', 'CPPIB'],
    description: 'Leading renewable energy IPP — 15 GW capacity across India',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-greenko',
    name: 'Greenko',
    industryId: 'ind-cleantech',
    country: 'India',
    founded: 2004,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '8B',
    mrrUSD: 150_000_000,
    employees: 2500,
    investors: ['GIC Singapore', 'ADIA', 'Orix Corp'],
    description: 'Integrated renewable energy storage solutions — pump hydro + solar',
    status: 'healthy',
    offset3D: O.e,
  },

  /* ──────────── Logistics ──────────── */
  {
    id: 'comp-delhivery',
    name: 'Delhivery',
    industryId: 'ind-logistics',
    country: 'India',
    founded: 2011,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'DELHIVERY.NS',
    valuation: '2.5B',
    mrrUSD: 200_000_000,
    employees: 12000,
    investors: [],
    description: 'India\'s largest fully-integrated logistics company — tech-first',
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-shadowfax',
    name: 'Shadowfax',
    industryId: 'ind-logistics',
    country: 'India',
    founded: 2015,
    stage: 'Series E',
    isPublic: false,
    valuation: '0.5B',
    mrrUSD: 20_000_000,
    employees: 3000,
    investors: ['IFC', 'Eight Roads', 'Mirae Asset'],
    description: 'Gig-economy logistics network for quick commerce and last mile',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-porter',
    name: 'Porter',
    industryId: 'ind-logistics',
    country: 'India',
    founded: 2014,
    stage: 'Series E',
    isPublic: false,
    valuation: '1.5B',
    mrrUSD: 25_000_000,
    employees: 2000,
    investors: ['Lightrock', 'Tiger Global', 'Sequoia'],
    description: 'Intra-city logistics marketplace — mini trucks on demand',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-shiprocket',
    name: 'Shiprocket',
    industryId: 'ind-logistics',
    country: 'India',
    founded: 2017,
    stage: 'Series E',
    isPublic: false,
    valuation: '1.3B',
    mrrUSD: 15_000_000,
    employees: 2500,
    investors: ['Bertelsmann', 'Temasek', 'March Capital'],
    description: 'E-commerce shipping aggregator for D2C brands and SMBs',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-xpressbees',
    name: 'XpressBees',
    industryId: 'ind-logistics',
    country: 'India',
    founded: 2015,
    stage: 'Series F',
    isPublic: false,
    valuation: '1B',
    mrrUSD: 30_000_000,
    employees: 3500,
    investors: ['TPG', 'Blackstone', 'CPPIB'],
    description: 'B2B logistics tech — express delivery, returns, warehousing',
    status: 'healthy',
    offset3D: O.e,
  },
  {
    id: 'comp-dunzo',
    name: 'Dunzo',
    industryId: 'ind-logistics',
    country: 'India',
    founded: 2015,
    stage: 'Series F',
    isPublic: false,
    valuation: '0.8B',
    mrrUSD: 8_000_000,
    employees: 2000,
    investors: ['Google', 'Reliance', 'Lightrock'],
    description: 'Quick-commerce and hyperlocal delivery — 19-min delivery',
    status: 'warning',
    offset3D: O.f,
  },

  /* ──────────── Gaming ──────────── */
  {
    id: 'comp-dream11',
    name: 'Dream11',
    industryId: 'ind-gaming',
    country: 'India',
    founded: 2008,
    stage: 'Series D+',
    isPublic: false,
    valuation: '8B',
    mrrUSD: 100_000_000,
    employees: 1500,
    investors: ['Tencent', 'Tiger Global', 'Steadview', 'DST Global'],
    description: "India's #1 fantasy sports platform — 200M+ users",
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-mpl',
    name: 'Mobile Premier League',
    industryId: 'ind-gaming',
    country: 'India',
    founded: 2018,
    stage: 'Series E',
    isPublic: false,
    valuation: '2.3B',
    mrrUSD: 15_000_000,
    employees: 800,
    investors: ['SoftBank', 'Go-Ventures', 'Telstra'],
    description: 'Skill-gaming platform — fantasy, puzzles, esports, casual games',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-nazara',
    name: 'Nazara Technologies',
    industryId: 'ind-gaming',
    country: 'India',
    founded: 2000,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'NAZARA.NS',
    valuation: '1B',
    mrrUSD: 12_000_000,
    employees: 900,
    investors: [],
    description: 'India\'s listed gaming company — esports, kids, interactive gaming',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-games24x7',
    name: 'Games24x7',
    industryId: 'ind-gaming',
    country: 'India',
    founded: 2006,
    stage: 'Series C',
    isPublic: false,
    valuation: '2.5B',
    mrrUSD: 20_000_000,
    employees: 600,
    investors: ['Tiger Global', 'Malabar Investments'],
    description: 'RummyCircle and My11Circle — India\'s top skill gaming operator',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-krafton',
    name: 'Krafton (BGMI India)',
    industryId: 'ind-gaming',
    country: 'South Korea',
    founded: 2007,
    stage: 'Public',
    isPublic: true,
    stockSymbol: '259960.KS',
    valuation: '5B',
    mrrUSD: 50_000_000,
    employees: 200,
    investors: [],
    description: 'PUBG and Battlegrounds Mobile India — battle-royale leader',
    status: 'healthy',
    offset3D: O.e,
  },

  /* ──────────── Mobility ──────────── */
  {
    id: 'comp-ola',
    name: 'Ola Cabs',
    industryId: 'ind-mobility',
    country: 'India',
    founded: 2010,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '6B',
    mrrUSD: 80_000_000,
    employees: 5000,
    investors: ['SoftBank', 'Tiger Global', 'Tencent'],
    description: "India's largest ride-hailing platform — 250 cities",
    status: 'warning',
    offset3D: O.a,
  },
  {
    id: 'comp-rapido',
    name: 'Rapido',
    industryId: 'ind-mobility',
    country: 'India',
    founded: 2015,
    stage: 'Series E',
    isPublic: false,
    valuation: '1.1B',
    mrrUSD: 25_000_000,
    employees: 1500,
    investors: ['Shell Ventures', 'Swiggy', 'WestBridge'],
    description: 'Bike taxi and auto aggregator — affordable urban mobility',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-blusmart',
    name: 'BluSmart',
    industryId: 'ind-mobility',
    country: 'India',
    founded: 2019,
    stage: 'Series B',
    isPublic: false,
    valuation: '0.5B',
    mrrUSD: 8_000_000,
    employees: 1000,
    investors: ['BP Ventures', 'Survam Partners', 'Green Frontier Capital'],
    description: 'India\'s first all-electric ride-hailing fleet — zero emissions',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-uber-in',
    name: 'Uber India',
    industryId: 'ind-mobility',
    country: 'USA',
    founded: 2010,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'UBER',
    valuation: '150B',
    mrrUSD: 200_000_000,
    employees: 32000,
    investors: [],
    description: 'Global ride-hailing and delivery — strong India presence',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-bounce',
    name: 'Bounce',
    industryId: 'ind-mobility',
    country: 'India',
    founded: 2014,
    stage: 'Series D+',
    isPublic: false,
    valuation: '0.4B',
    mrrUSD: 3_000_000,
    employees: 500,
    investors: ['Accel', 'Sequoia', 'B Capital'],
    description: 'Dockless bike-sharing and EV two-wheeler rentals',
    status: 'warning',
    offset3D: O.e,
  },

  /* ──────────── Media ──────────── */
  {
    id: 'comp-sharechat',
    name: 'ShareChat',
    industryId: 'ind-media',
    country: 'India',
    founded: 2015,
    stage: 'Series H',
    isPublic: false,
    valuation: '5B',
    mrrUSD: 10_000_000,
    employees: 2000,
    investors: ['Times Group', 'Twitter', 'Google', 'Temasek', 'Tiger Global'],
    description: 'India\'s leading vernacular social media — 15 languages, 180M MAU',
    status: 'warning',
    offset3D: O.a,
  },
  {
    id: 'comp-inshorts',
    name: 'Inshorts',
    industryId: 'ind-media',
    country: 'India',
    founded: 2013,
    stage: 'Series D+',
    isPublic: false,
    valuation: '0.6B',
    mrrUSD: 3_000_000,
    employees: 500,
    investors: ['Tiger Global', 'SoftBank', 'Tanglin Venture Partners'],
    description: 'News in 60 words — AI-powered news aggregation platform',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-dailyhunt',
    name: 'Dailyhunt (VerSe)',
    industryId: 'ind-media',
    country: 'India',
    founded: 2009,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '5B',
    mrrUSD: 15_000_000,
    employees: 2000,
    investors: ['ByteDance', 'Google', 'Microsoft', 'Qatar Investment Authority'],
    description: 'India\'s top local language content platform — news + short video',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-josh',
    name: 'Josh (VerSe)',
    industryId: 'ind-media',
    country: 'India',
    founded: 2020,
    stage: 'Series D+',
    isPublic: false,
    valuation: '5B',
    mrrUSD: 12_000_000,
    employees: 2500,
    investors: ['ByteDance', 'Google', 'Microsoft'],
    description: 'Short-video platform (post-TikTok ban) — 180M+ users',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-youtube-in',
    name: 'YouTube India',
    industryId: 'ind-media',
    country: 'USA',
    founded: 2005,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'GOOGL',
    valuation: '450B',
    mrrUSD: 5_000_000_000,
    employees: 100_000,
    investors: [],
    description: 'World\'s largest video platform — 467M Indian users',
    status: 'healthy',
    offset3D: O.e,
  },

  /* ──────────── AgriTech ──────────── */
  {
    id: 'comp-dehaat',
    name: 'DeHaat',
    industryId: 'ind-agritech',
    country: 'India',
    founded: 2012,
    stage: 'Series F',
    isPublic: false,
    valuation: '1.2B',
    mrrUSD: 15_000_000,
    employees: 3000,
    investors: ['Prosus', 'SoftBank', 'Lightrock', 'Sequoia'],
    description: 'Full-stack agri platform — inputs, advisory, and market linkage',
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-ninjacart',
    name: 'Ninjacart',
    industryId: 'ind-agritech',
    country: 'India',
    founded: 2015,
    stage: 'Series D+',
    isPublic: false,
    valuation: '1.5B',
    mrrUSD: 20_000_000,
    employees: 2500,
    investors: ['Tiger Global', 'Walmart', 'Flipkart', 'Accel'],
    description: 'Fresh produce B2B supply chain — farm to kirana in 12 hours',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-agrostar',
    name: 'AgroStar',
    industryId: 'ind-agritech',
    country: 'India',
    founded: 2013,
    stage: 'Series D+',
    isPublic: false,
    valuation: '0.5B',
    mrrUSD: 5_000_000,
    employees: 1000,
    investors: ['Bertelsmann', 'Accel', 'Aavishkaar Capital'],
    description: 'Direct-to-farmer agri-input e-commerce and agronomy advisory',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-cropin',
    name: 'CropIn',
    industryId: 'ind-agritech',
    country: 'India',
    founded: 2010,
    stage: 'Series C',
    isPublic: false,
    valuation: '0.4B',
    mrrUSD: 3_000_000,
    employees: 500,
    investors: ['ABC World Asia', 'Chiratae Ventures', 'Columbia Threadneedle'],
    description: 'AI-powered farm management and supply chain intelligence SaaS',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-bighaat',
    name: 'BigHaat',
    industryId: 'ind-agritech',
    country: 'India',
    founded: 2015,
    stage: 'Series B',
    isPublic: false,
    valuation: '0.2B',
    mrrUSD: 2_000_000,
    employees: 400,
    investors: ['Omnivore', 'Arkam Ventures', 'SBI Investment'],
    description: 'Agri-input marketplace and agri advisory for smallholder farmers',
    status: 'healthy',
    offset3D: O.e,
  },

  /* ──────────── Cybersecurity ──────────── */
  {
    id: 'comp-quickheal',
    name: 'Quick Heal',
    industryId: 'ind-cyber',
    country: 'India',
    founded: 1993,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'QUICKHEAL.NS',
    valuation: '0.6B',
    mrrUSD: 10_000_000,
    employees: 1700,
    investors: [],
    description: 'India\'s largest cybersecurity product company — consumer + enterprise',
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-tac',
    name: 'TAC Security',
    industryId: 'ind-cyber',
    country: 'India',
    founded: 2013,
    stage: 'Series A',
    isPublic: false,
    valuation: '0.1B',
    mrrUSD: 1_500_000,
    employees: 200,
    investors: ['Sequoia Surge'],
    description: 'Enterprise VAPT and vulnerability management platform',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-paloalto',
    name: 'Palo Alto Networks',
    industryId: 'ind-cyber',
    country: 'USA',
    founded: 2005,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'PANW',
    valuation: '120B',
    mrrUSD: 500_000_000,
    employees: 14000,
    investors: [],
    description: 'Global NGFW, SASE, and cloud security leader',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-crowdstrike',
    name: 'CrowdStrike',
    industryId: 'ind-cyber',
    country: 'USA',
    founded: 2011,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'CRWD',
    valuation: '90B',
    mrrUSD: 250_000_000,
    employees: 9000,
    investors: [],
    description: 'Cloud-native endpoint and identity protection platform',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-cloudsek',
    name: 'CloudSEK',
    industryId: 'ind-cyber',
    country: 'India',
    founded: 2016,
    stage: 'Series B',
    isPublic: false,
    valuation: '0.2B',
    mrrUSD: 1_000_000,
    employees: 200,
    investors: ['MassMutual Ventures', 'Infoedge Ventures'],
    description: 'AI-powered digital risk monitoring — dark web, brand, infra threats',
    status: 'healthy',
    offset3D: O.e,
  },

  /* ──────────── SpaceTech ──────────── */
  {
    id: 'comp-agnikul',
    name: 'AgniKul Cosmos',
    industryId: 'ind-space',
    country: 'India',
    founded: 2017,
    stage: 'Series B',
    isPublic: false,
    valuation: '0.3B',
    mrrUSD: 500_000,
    employees: 100,
    investors: ['Mayfield', 'pi Ventures', 'Artha Venture Fund'],
    description: 'World\'s first 3D-printed rocket engine — semi-cryogenic Agnibaan',
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-skyroot',
    name: 'Skyroot Aerospace',
    industryId: 'ind-space',
    country: 'India',
    founded: 2018,
    stage: 'Series B',
    isPublic: false,
    valuation: '0.4B',
    mrrUSD: 800_000,
    employees: 180,
    investors: ['GrowX Ventures', 'Solar Industries', 'HNIs'],
    description: 'India\'s first private orbital rocket — Vikram series',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-pixxel',
    name: 'Pixxel',
    industryId: 'ind-space',
    country: 'India',
    founded: 2019,
    stage: 'Series B',
    isPublic: false,
    valuation: '0.5B',
    mrrUSD: 1_000_000,
    employees: 150,
    investors: ['Google', 'Radical Ventures', 'Blume Ventures'],
    description: 'Hyperspectral earth-observation satellite constellation',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-spacex',
    name: 'SpaceX',
    industryId: 'ind-space',
    country: 'USA',
    founded: 2002,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '175B',
    mrrUSD: 400_000_000,
    employees: 12000,
    investors: ['Founders Fund', 'Baillie Gifford', 'Fidelity'],
    description: 'Reusable rockets, Starlink satellite internet, Mars mission',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-isro',
    name: 'ISRO',
    industryId: 'ind-space',
    country: 'India',
    founded: 1969,
    stage: 'PSU',
    isPublic: false,
    valuation: 'PSU',
    mrrUSD: 250_000_000,
    employees: 16000,
    investors: ['Government of India'],
    description: 'Indian Space Research Organisation — Chandrayaan, Aditya, PSLV',
    status: 'healthy',
    offset3D: O.e,
  },

  /* ──────────── PropTech ──────────── */
  {
    id: 'comp-nobroker',
    name: 'NoBroker',
    industryId: 'ind-proptech',
    country: 'India',
    founded: 2014,
    stage: 'Series E',
    isPublic: false,
    valuation: '1B',
    mrrUSD: 10_000_000,
    employees: 4000,
    investors: ['General Atlantic', 'Tiger Global', 'Moore Strategic Ventures'],
    description: "India's first proptech unicorn — zero-brokerage property marketplace",
    status: 'healthy',
    offset3D: O.a,
  },
  {
    id: 'comp-squareyards',
    name: 'Square Yards',
    industryId: 'ind-proptech',
    country: 'India',
    founded: 2014,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '0.7B',
    mrrUSD: 8_000_000,
    employees: 3000,
    investors: ['Amit Bachchan', 'Tejasvi Surya', 'Malabar Investments'],
    description: 'Full-stack real estate platform — primary, rental, mortgages',
    status: 'healthy',
    offset3D: O.b,
  },
  {
    id: 'comp-housing',
    name: 'Housing.com',
    industryId: 'ind-proptech',
    country: 'India',
    founded: 2012,
    stage: 'Pre-IPO',
    isPublic: false,
    valuation: '0.5B',
    mrrUSD: 5_000_000,
    employees: 1500,
    investors: ['Info Edge (PropTiger merger)'],
    description: 'Online real estate search with AI pricing and verified listings',
    status: 'healthy',
    offset3D: O.c,
  },
  {
    id: 'comp-magicbricks',
    name: 'MagicBricks',
    industryId: 'ind-proptech',
    country: 'India',
    founded: 2006,
    stage: 'Public',
    isPublic: true,
    stockSymbol: 'TIMESGROUP',
    valuation: '0.6B',
    mrrUSD: 6_000_000,
    employees: 1200,
    investors: ['Times Group'],
    description: 'India\'s leading property search platform — buy, sell, rent',
    status: 'healthy',
    offset3D: O.d,
  },
  {
    id: 'comp-nestaway',
    name: 'Nestaway',
    industryId: 'ind-proptech',
    country: 'India',
    founded: 2015,
    stage: 'Series E',
    isPublic: false,
    valuation: '0.2B',
    mrrUSD: 2_000_000,
    employees: 500,
    investors: ['IDG Ventures', 'Tiger Global', 'Goldman Sachs'],
    description: 'Managed rental housing for working professionals',
    status: 'warning',
    offset3D: O.e,
  },
];

export const COMPANY_MAP = new Map<string, CompanyRecord>(
  COMPANIES.map(c => [c.id, c])
);
