-- ================================================================
-- FounderOS — Workspace Invites + Join Requests
-- Migration 003
-- ================================================================

-- ----------------------------------------------------------------
-- member_status enum — track where a member is in the lifecycle
-- ----------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE member_status AS ENUM ('pending', 'active', 'rejected', 'removed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ----------------------------------------------------------------
-- Add status column to company_members if not exists
-- ----------------------------------------------------------------
ALTER TABLE company_members
  ADD COLUMN IF NOT EXISTS status      member_status NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS approved_by UUID REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;

-- ----------------------------------------------------------------
-- workspace_invites — invite links generated by founders/admins
-- Each link has a token, optional role cap, optional email target
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS workspace_invites (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id    UUID        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  token         TEXT        UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(24), 'base64url'),
  role          user_role   NOT NULL DEFAULT 'viewer',
  email         TEXT,                        -- null = open link, set = targeted invite
  created_by    UUID        NOT NULL REFERENCES auth.users(id),
  expires_at    TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
  max_uses      INTEGER     NOT NULL DEFAULT 1,
  used_count    INTEGER     NOT NULL DEFAULT 0,
  is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- join_requests — someone finds the company and requests access
-- Created when: user signs up and wants to join an existing company
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS join_requests (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id    UUID        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id       UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  requested_role user_role  NOT NULL DEFAULT 'viewer',
  message       TEXT,                        -- optional note from the requester
  status        TEXT        NOT NULL DEFAULT 'pending',  -- pending | approved | rejected
  reviewed_by   UUID        REFERENCES auth.users(id),
  reviewed_at   TIMESTAMPTZ,
  assigned_role user_role,                   -- role actually assigned on approval
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (company_id, user_id)               -- one request per user per company
);

-- ----------------------------------------------------------------
-- RLS Policies — workspace_invites
-- ----------------------------------------------------------------
ALTER TABLE workspace_invites ENABLE ROW LEVEL SECURITY;

-- Founders/admins can see invites for their company
CREATE POLICY "invite_select_member" ON workspace_invites
  FOR SELECT USING (
    company_id IN (
      SELECT company_id FROM company_members
      WHERE user_id = auth.uid() AND status = 'active'
    )
  );

-- Founders/admins/co-founders can create invite links
CREATE POLICY "invite_insert_admin" ON workspace_invites
  FOR INSERT WITH CHECK (
    company_id IN (
      SELECT company_id FROM company_members
      WHERE user_id = auth.uid()
        AND status = 'active'
        AND role IN ('founder', 'co_founder', 'admin', 'super_admin')
    )
  );

-- Founders/admins can deactivate invites
CREATE POLICY "invite_update_admin" ON workspace_invites
  FOR UPDATE USING (
    company_id IN (
      SELECT company_id FROM company_members
      WHERE user_id = auth.uid()
        AND status = 'active'
        AND role IN ('founder', 'co_founder', 'admin', 'super_admin')
    )
  );

-- Anyone can read an invite by token (for join link flow — no auth required)
CREATE POLICY "invite_select_by_token" ON workspace_invites
  FOR SELECT USING (is_active = TRUE AND expires_at > NOW());

-- ----------------------------------------------------------------
-- RLS Policies — join_requests
-- ----------------------------------------------------------------
ALTER TABLE join_requests ENABLE ROW LEVEL SECURITY;

-- Users see their own requests
CREATE POLICY "joinreq_select_self" ON join_requests
  FOR SELECT USING (user_id = auth.uid());

-- Founders/admins see all requests for their company
CREATE POLICY "joinreq_select_admin" ON join_requests
  FOR SELECT USING (
    company_id IN (
      SELECT company_id FROM company_members
      WHERE user_id = auth.uid()
        AND status = 'active'
        AND role IN ('founder', 'co_founder', 'admin', 'super_admin')
    )
  );

-- Any authenticated user can submit a join request
CREATE POLICY "joinreq_insert_self" ON join_requests
  FOR INSERT WITH CHECK (user_id = auth.uid());

-- Founders/admins can update (approve/reject)
CREATE POLICY "joinreq_update_admin" ON join_requests
  FOR UPDATE USING (
    company_id IN (
      SELECT company_id FROM company_members
      WHERE user_id = auth.uid()
        AND status = 'active'
        AND role IN ('founder', 'co_founder', 'admin', 'super_admin')
    )
  );

-- ----------------------------------------------------------------
-- RLS Policies — company_members (add missing policies)
-- ----------------------------------------------------------------
ALTER TABLE company_members ENABLE ROW LEVEL SECURITY;

-- Members can see other members of their own company
CREATE POLICY "members_select" ON company_members
  FOR SELECT USING (
    company_id IN (
      SELECT company_id FROM company_members cm2
      WHERE cm2.user_id = auth.uid()
    )
  );

-- Founders/admins can insert new members
CREATE POLICY "members_insert_admin" ON company_members
  FOR INSERT WITH CHECK (
    company_id IN (
      SELECT company_id FROM company_members
      WHERE user_id = auth.uid()
        AND status = 'active'
        AND role IN ('founder', 'co_founder', 'admin', 'super_admin')
    )
  );

-- Founders/admins can update roles and status
CREATE POLICY "members_update_admin" ON company_members
  FOR UPDATE USING (
    company_id IN (
      SELECT company_id FROM company_members
      WHERE user_id = auth.uid()
        AND status = 'active'
        AND role IN ('founder', 'co_founder', 'admin', 'super_admin')
    )
  );

-- Founders can delete (remove) members
CREATE POLICY "members_delete_founder" ON company_members
  FOR DELETE USING (
    company_id IN (
      SELECT company_id FROM company_members
      WHERE user_id = auth.uid()
        AND status = 'active'
        AND role IN ('founder', 'co_founder', 'super_admin')
    )
  );

-- ----------------------------------------------------------------
-- Helper function: accept an invite token
-- Called when a user clicks a join link. Returns success/error.
-- ----------------------------------------------------------------
CREATE OR REPLACE FUNCTION accept_invite(p_token TEXT, p_user_id UUID)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_invite workspace_invites%ROWTYPE;
  v_existing company_members%ROWTYPE;
BEGIN
  -- Find and lock the invite
  SELECT * INTO v_invite
  FROM workspace_invites
  WHERE token = p_token
    AND is_active = TRUE
    AND expires_at > NOW()
    AND (max_uses = 0 OR used_count < max_uses)
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invite link is invalid or expired');
  END IF;

  -- Check if email-targeted invite matches the user
  IF v_invite.email IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM auth.users WHERE id = p_user_id AND email = v_invite.email
    ) THEN
      RETURN jsonb_build_object('success', false, 'error', 'This invite was sent to a different email address');
    END IF;
  END IF;

  -- Check not already a member
  SELECT * INTO v_existing
  FROM company_members
  WHERE company_id = v_invite.company_id AND user_id = p_user_id;

  IF FOUND THEN
    IF v_existing.status = 'active' THEN
      RETURN jsonb_build_object('success', false, 'error', 'You are already a member of this workspace');
    END IF;
    -- Re-activate if previously removed
    UPDATE company_members
    SET status = 'active', role = v_invite.role, approved_at = NOW()
    WHERE id = v_existing.id;
  ELSE
    -- Add as active member immediately (invite = pre-approved)
    INSERT INTO company_members (company_id, user_id, role, status, invited_by, approved_at)
    VALUES (v_invite.company_id, p_user_id, v_invite.role, 'active', v_invite.created_by, NOW());
  END IF;

  -- Update user_profiles to link company
  UPDATE user_profiles
  SET company_id = v_invite.company_id,
      role = v_invite.role,
      onboarding_completed = TRUE,
      updated_at = NOW()
  WHERE id = p_user_id;

  -- Increment usage
  UPDATE workspace_invites
  SET used_count = used_count + 1,
      is_active = CASE WHEN used_count + 1 >= max_uses AND max_uses > 0 THEN FALSE ELSE is_active END
  WHERE id = v_invite.id;

  RETURN jsonb_build_object(
    'success', true,
    'company_id', v_invite.company_id,
    'role', v_invite.role
  );
END;
$$;

-- ----------------------------------------------------------------
-- Helper function: approve a join request
-- ----------------------------------------------------------------
CREATE OR REPLACE FUNCTION approve_join_request(
  p_request_id UUID,
  p_reviewer_id UUID,
  p_assigned_role user_role DEFAULT 'viewer'
)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_req join_requests%ROWTYPE;
BEGIN
  SELECT * INTO v_req FROM join_requests WHERE id = p_request_id AND status = 'pending';
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Request not found or already processed');
  END IF;

  -- Add to company_members
  INSERT INTO company_members (company_id, user_id, role, status, invited_by, approved_at)
  VALUES (v_req.company_id, v_req.user_id, p_assigned_role, 'active', p_reviewer_id, NOW())
  ON CONFLICT (company_id, user_id) DO UPDATE
    SET role = p_assigned_role, status = 'active', approved_at = NOW();

  -- Update user_profiles
  UPDATE user_profiles
  SET company_id = v_req.company_id,
      role = p_assigned_role,
      onboarding_completed = TRUE,
      updated_at = NOW()
  WHERE id = v_req.user_id;

  -- Mark request as approved
  UPDATE join_requests
  SET status = 'approved', reviewed_by = p_reviewer_id,
      reviewed_at = NOW(), assigned_role = p_assigned_role
  WHERE id = p_request_id;

  RETURN jsonb_build_object('success', true);
END;
$$;
