-- ================================================================
-- 011_seed_subdomains_full.sql
-- Full upsert of all subdomains across 12 industries.
-- Idempotent: safe to re-run (ON CONFLICT DO NOTHING).
-- ================================================================

INSERT INTO subdomains (id, industry_id, label, description, orbit_index, color)
VALUES
  ('sd-tech-ai', 'ind-technology', 'AI', NULL, 0, '#818cf8'),
  ('sd-tech-cloud', 'ind-technology', 'Cloud', NULL, 1, '#818cf8'),
  ('sd-tech-cyber', 'ind-technology', 'Cybersecurity', NULL, 2, '#818cf8'),
  ('sd-tech-hardware', 'ind-technology', 'Hardware', NULL, 3, '#818cf8'),
  ('sd-tech-web3', 'ind-technology', 'Web3', NULL, 4, '#818cf8'),
  ('sd-tech-enterprise', 'ind-technology', 'Enterprise Software', NULL, 5, '#818cf8'),
  ('sd-tech-software', 'ind-technology', 'Software', NULL, 6, '#818cf8'),
  ('sd-fin-fintech', 'ind-finance', 'Fintech', NULL, 0, '#22d3ee'),
  ('sd-fin-banking', 'ind-finance', 'Banking', NULL, 1, '#22d3ee'),
  ('sd-fin-insurance', 'ind-finance', 'Insurance', NULL, 2, '#22d3ee'),
  ('sd-fin-investing', 'ind-finance', 'Investing', NULL, 3, '#22d3ee'),
  ('sd-fin-trading', 'ind-finance', 'Trading', NULL, 4, '#22d3ee'),
  ('sd-fin-asset', 'ind-finance', 'Asset Management', NULL, 5, '#22d3ee'),
  ('sd-fin-lending', 'ind-finance', 'Lending', NULL, 6, '#22d3ee'),
  ('sd-mfg-automotive', 'ind-manufacturing', 'Automotive', NULL, 0, '#fb923c'),
  ('sd-mfg-electronics', 'ind-manufacturing', 'Electronics', NULL, 1, '#fb923c'),
  ('sd-mfg-industrial', 'ind-manufacturing', 'Industrial Machinery', NULL, 2, '#fb923c'),
  ('sd-mfg-consumer', 'ind-manufacturing', 'Consumer Goods', NULL, 3, '#fb923c'),
  ('sd-mfg-textiles', 'ind-manufacturing', 'Textiles', NULL, 4, '#fb923c'),
  ('sd-mfg-supply', 'ind-manufacturing', 'Supply Chain Systems', NULL, 5, '#fb923c'),
  ('sd-mfg-heavy', 'ind-manufacturing', 'Heavy Industry', NULL, 6, '#fb923c'),
  ('sd-health-pharma', 'ind-healthcare', 'Pharma', NULL, 0, '#34d399'),
  ('sd-health-biotech', 'ind-healthcare', 'Biotech', NULL, 1, '#34d399'),
  ('sd-health-hospitals', 'ind-healthcare', 'Hospitals', NULL, 2, '#34d399'),
  ('sd-health-diag', 'ind-healthcare', 'Diagnostics', NULL, 3, '#34d399'),
  ('sd-health-preventive', 'ind-healthcare', 'Preventive Care', NULL, 4, '#34d399'),
  ('sd-health-mental', 'ind-healthcare', 'Mental Health', NULL, 5, '#34d399'),
  ('sd-health-devices', 'ind-healthcare', 'Medical Devices', NULL, 6, '#34d399'),
  ('sd-health-digital', 'ind-healthcare', 'Healthtech', NULL, 7, '#34d399'),
  ('sd-edu-schools', 'ind-education', 'Schools', NULL, 0, '#a78bfa'),
  ('sd-edu-universities', 'ind-education', 'Universities', NULL, 1, '#a78bfa'),
  ('sd-edu-edtech', 'ind-education', 'Edtech', NULL, 2, '#a78bfa'),
  ('sd-edu-testprep', 'ind-education', 'Test Prep', NULL, 3, '#a78bfa'),
  ('sd-edu-publishing', 'ind-education', 'Knowledge Publishing', NULL, 4, '#a78bfa'),
  ('sd-edu-research', 'ind-education', 'Research Institutions', NULL, 5, '#a78bfa'),
  ('sd-edu-corporate', 'ind-education', 'Corporate Training', NULL, 6, '#a78bfa'),
  ('sd-edu-skills', 'ind-education', 'Skill Platforms', NULL, 7, '#a78bfa'),
  ('sd-med-film', 'ind-media', 'Film', NULL, 0, '#f43f5e'),
  ('sd-med-tv', 'ind-media', 'Television', NULL, 1, '#f43f5e'),
  ('sd-med-streaming', 'ind-media', 'Streaming', NULL, 2, '#f43f5e'),
  ('sd-med-music', 'ind-media', 'Music', NULL, 3, '#f43f5e'),
  ('sd-med-gaming', 'ind-media', 'Gaming', NULL, 4, '#f43f5e'),
  ('sd-med-sports-med', 'ind-media', 'Sports Media', NULL, 5, '#f43f5e'),
  ('sd-med-sports-econ', 'ind-media', 'Sports Economy', NULL, 6, '#f43f5e'),
  ('sd-med-creator', 'ind-media', 'Creator Economy', NULL, 7, '#f43f5e'),
  ('sd-com-retail', 'ind-commerce', 'Retail', NULL, 0, '#f472b6'),
  ('sd-com-ecommerce', 'ind-commerce', 'E-commerce', NULL, 1, '#f472b6'),
  ('sd-com-d2c', 'ind-commerce', 'D2C Brands', NULL, 2, '#f472b6'),
  ('sd-com-marketplaces', 'ind-commerce', 'Marketplaces', NULL, 3, '#f472b6'),
  ('sd-com-wholesale', 'ind-commerce', 'Wholesale', NULL, 4, '#f472b6'),
  ('sd-com-consumer', 'ind-commerce', 'Consumer Platforms', NULL, 5, '#f472b6'),
  ('sd-com-cx', 'ind-commerce', 'CX Systems', NULL, 6, '#f472b6'),
  ('sd-en-solar', 'ind-energy', 'Solar', NULL, 0, '#4ade80'),
  ('sd-en-wind', 'ind-energy', 'Wind', NULL, 1, '#4ade80'),
  ('sd-en-storage', 'ind-energy', 'Storage', NULL, 2, '#4ade80'),
  ('sd-en-ev', 'ind-energy', 'EV Infrastructure', NULL, 3, '#4ade80'),
  ('sd-en-carbon', 'ind-energy', 'Carbon Management', NULL, 4, '#4ade80'),
  ('sd-en-waste-sys', 'ind-energy', 'Waste Systems', NULL, 5, '#4ade80'),
  ('sd-en-waste', 'ind-energy', 'Waste Management', NULL, 6, '#4ade80'),
  ('sd-en-climate', 'ind-energy', 'Climate Tech', NULL, 7, '#4ade80'),
  ('sd-gov-governance', 'ind-government', 'Governance', NULL, 0, '#64748b'),
  ('sd-gov-defense', 'ind-government', 'Defense', NULL, 1, '#64748b'),
  ('sd-gov-policy', 'ind-government', 'Public Policy', NULL, 2, '#64748b'),
  ('sd-gov-civic', 'ind-government', 'Civic Tech', NULL, 3, '#64748b'),
  ('sd-gov-welfare', 'ind-government', 'Social Welfare', NULL, 4, '#64748b'),
  ('sd-gov-pubhealth', 'ind-government', 'Public Health Systems', NULL, 5, '#64748b'),
  ('sd-gov-social', 'ind-government', 'Social Systems', NULL, 6, '#64748b'),
  ('sd-gov-sust', 'ind-government', 'Sust Tech', NULL, 7, '#64748b'),
  ('sd-mob-aviation', 'ind-mobility', 'Aviation', NULL, 0, '#38bdf8'),
  ('sd-mob-rail', 'ind-mobility', 'Rail', NULL, 1, '#38bdf8'),
  ('sd-mob-logistics', 'ind-mobility', 'Logistics', NULL, 2, '#38bdf8'),
  ('sd-mob-shipping', 'ind-mobility', 'Shipping', NULL, 3, '#38bdf8'),
  ('sd-mob-travel', 'ind-mobility', 'Travel Infrastructure', NULL, 4, '#38bdf8'),
  ('sd-mob-delivery', 'ind-mobility', 'Delivery Systems', NULL, 5, '#38bdf8'),
  ('sd-mob-auto', 'ind-mobility', 'Automotive Mobility', NULL, 6, '#38bdf8'),
  ('sd-re-residential', 'ind-realestate', 'Residential', NULL, 0, '#fdba74'),
  ('sd-re-commercial', 'ind-realestate', 'Commercial', NULL, 1, '#fdba74'),
  ('sd-re-construction', 'ind-realestate', 'Construction', NULL, 2, '#fdba74'),
  ('sd-re-facility', 'ind-realestate', 'Facility Management', NULL, 3, '#fdba74'),
  ('sd-re-smart', 'ind-realestate', 'Smart Management', NULL, 4, '#fdba74'),
  ('sd-re-proptech', 'ind-realestate', 'Proptech', NULL, 5, '#fdba74'),
  ('sd-agri-farming', 'ind-agriculture', 'Farming', NULL, 0, '#86efac'),
  ('sd-agri-agritech', 'ind-agriculture', 'Agri-tech', NULL, 1, '#86efac'),
  ('sd-agri-food', 'ind-agriculture', 'Food Processing', NULL, 2, '#86efac'),
  ('sd-agri-fisheries', 'ind-agriculture', 'Fisheries', NULL, 3, '#86efac'),
  ('sd-agri-supply-del', 'ind-agriculture', 'Supply Delivery', NULL, 4, '#86efac'),
  ('sd-agri-market', 'ind-agriculture', 'Market Discovery', NULL, 5, '#86efac')
ON CONFLICT (id) DO NOTHING;
